#!/bin/bash
# Complete OAuth flow testing script for all Keycloak users
# This script helps test each user systematically

echo "=========================================="
echo "Keycloak User Testing - Complete Flow"
echo "=========================================="
echo ""
echo "Frontend: http://localhost:3001/auth/login"
echo "Backend: http://localhost:8000"
echo "Password for all users: Test123!"
echo ""
echo "Users to test:"
echo "1. uber-admin (uber_admin)"
echo "2. tenant-admin-1 (tenant_admin)"
echo "3. tenant-admin-2 (tenant_admin)"
echo "4. project-admin-1 (project_admin)"
echo "5. end-user-1 (end_user)"
echo "6. end-user-2 (end_user)"
echo "7. end-user-3 (end_user)"
echo ""
echo "For each user:"
echo "1. Go to http://localhost:3001/auth/login"
echo "2. Click 'Sign in with OAuth 2.0'"
echo "3. Login with username/password"
echo "4. Verify successful authentication"
echo "5. Check role and tenant_id in UI"
echo "6. Logout"
echo ""
echo "Starting tests..."
